### ISSUE TITLE
Allow customizing Jackson ObjectMapper

### ISSUE THREAD

**Issue by tgolden-andplus** [serialized-io/client-java#1]
It would be great if we could customize the ObjectMapper instance used by the `SerializedClientConfig` builder. For example, registering additional modules, such as the `JavaTimeModule` to correctly serialize/deserialize `java.time.Instant`.

One possible hook would be to add a method to the config builder that accepts a callback like so:

```
SerializedClientConfig.serializedConfig()
  .configureObjectMapper(objectMapper -> {
    objectMapper.registerModule(new JavaTimeModule());
  })
  .build()
```

**Comment by mattiasholmqvist** [comment]
You can configure the objectMapper by accessing it from the config, like this:
```
SerializedClientConfig serializedClientConfig = SerializedClientConfig.serializedConfig()
        .accessKey(accessKey)
        .secretAccessKey(secretKey)
        .build();

serializedClientConfig.objectMapper().registerModule(module);
```
You currently need to build the config object before you can configure the objectMapper.

Hope this helps!

**Comment by tgolden-andplus** [comment]
Somehow I missed that there was a public accessor method for the mapper... 🤦‍♂️ thank you!

**Comment by tgolden-andplus** [comment]
Actually, I have to reopen this. The `ObjectMapper` comes from a `Supplier` method, so a fresh instance is returned every time...thus, configuring the returned instance from `config.objectMapper()` is no good, as that configuration won't be used when the aggregate client and friends actually serialize/deserialize objects!

**Comment by mattiasholmqvist** [comment]
You are correct, sorry for misleading you. The reason the `objectMapper()` method is public is to allow for the different clients in the library to access it. We originally decided to not allow it to be modified since it may cause the library to break if you are not careful.

We normally map fields manually in the event classes to avoid as much implicit Jackson mapping as possible, but I can see that it makes sense for others to do it differently. 

Just to get the full picture, is it particularly registering modules (such as Java time) or are there other things you also want to configure on the ObjectMapper?
